[0m14:01:06.077114 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002240F91E830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002240EA3AA40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002240EA3AC50>]}


============================== 14:01:06.086117 | 46866f3f-47b2-47da-96d9-ad4deb1dfe91 ==============================
[0m14:01:06.086117 [info ] [MainThread]: Running with dbt=1.6.1
[0m14:01:06.088116 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init jaffle_shop', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:01:06.089117 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/kerry/.dbt')}
[0m14:01:06.090118 [info ] [MainThread]: Creating dbt configuration folder at
[0m14:01:06.092116 [debug] [MainThread]: Starter project path: D:\E\dbt_core_jaffle_shop\.venv\lib\site-packages\dbt\include\starter_project
[0m14:01:06.163116 [info ] [MainThread]:
Your new dbt project "jaffle_shop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:01:06.166118 [info ] [MainThread]: Setting up your profile.
[0m14:15:22.134819 [info ] [MainThread]: Profile jaffle_shop written to C:\Users\kerry\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:15:22.136817 [debug] [MainThread]: Command `dbt init` succeeded at 14:15:22.136817 after 856.07 seconds
[0m14:15:22.137818 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002240F91E830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022412D610F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022412D63130>]}
[0m14:15:22.138819 [debug] [MainThread]: Flushing usage events
[0m15:04:05.623188 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6FF88E890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D68223B670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D68223B430>]}


============================== 15:04:05.628290 | 5116a0ae-978b-4e81-96f0-93ec816a635b ==============================
[0m15:04:05.628290 [info ] [MainThread]: Running with dbt=1.6.1
[0m15:04:05.629272 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run -m customers', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:04:05.630290 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m15:04:05.632281 [debug] [MainThread]: Command `dbt run` failed at 15:04:05.632281 after 0.03 seconds
[0m15:04:05.633288 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6FF88E890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D68223B400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D68223B6D0>]}
[0m15:04:05.634285 [debug] [MainThread]: Flushing usage events
[0m15:04:34.743677 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F22362860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F2147B5E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F2147B400>]}


============================== 15:04:34.748654 | c8c5b0f6-6995-46e5-9441-b0a54a2ac1f4 ==============================
[0m15:04:34.748654 [info ] [MainThread]: Running with dbt=1.6.1
[0m15:04:34.749656 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:04:34.749656 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m15:04:34.752658 [debug] [MainThread]: Command `dbt run` failed at 15:04:34.751654 after 0.03 seconds
[0m15:04:34.752658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F22362860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F2147B310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F2147B640>]}
[0m15:04:34.753671 [debug] [MainThread]: Flushing usage events
[0m17:21:35.466561 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027ADAD8E8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AD9EAB6A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AD9EAB4C0>]}


============================== 17:21:35.470561 | ef2e6338-0a51-45ba-b583-2cac364a2100 ==============================
[0m17:21:35.470561 [info ] [MainThread]: Running with dbt=1.6.1
[0m17:21:35.471547 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt compile -m stg_customers', 'send_anonymous_usage_stats': 'True'}
[0m17:21:35.472547 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m17:21:35.474562 [debug] [MainThread]: Command `dbt compile` failed at 17:21:35.474562 after 0.03 seconds
[0m17:21:35.475545 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027ADAD8E8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AD9EAB3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AD9EAB700>]}
[0m17:21:35.475545 [debug] [MainThread]: Flushing usage events
[0m21:34:36.142800 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAFB1BE8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAFA2BB730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAFA2BB550>]}


============================== 21:34:36.183880 | 8d7bd116-33a4-4cab-8047-ae2157b30b07 ==============================
[0m21:34:36.183880 [info ] [MainThread]: Running with dbt=1.6.1
[0m21:34:36.184895 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt docs generate', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:34:36.185893 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m21:34:36.186893 [debug] [MainThread]: Command `dbt docs generate` failed at 21:34:36.186893 after 0.08 seconds
[0m21:34:36.187893 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAFB1BE8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAFA2BB460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAFA2BB790>]}
[0m21:34:36.188902 [debug] [MainThread]: Flushing usage events
[0m21:36:42.327370 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296FEFDE830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002968195B6A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002968195B460>]}


============================== 21:36:42.332388 | 5c742a8e-39bf-40a5-9160-dbecf029649d ==============================
[0m21:36:42.332388 [info ] [MainThread]: Running with dbt=1.6.1
[0m21:36:42.333397 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt docs generate', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:36:42.334373 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m21:36:42.335372 [debug] [MainThread]: Command `dbt docs generate` failed at 21:36:42.335372 after 0.02 seconds
[0m21:36:42.336387 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296FEFDE830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002968195B3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002968195B700>]}
[0m21:36:42.337374 [debug] [MainThread]: Flushing usage events
[0m21:44:25.756521 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C6C6D7E890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C6C5E7B700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C6C5E7B4C0>]}


============================== 21:44:25.761523 | 237a8a94-b0fe-4427-a05e-5408781d7dd3 ==============================
[0m21:44:25.761523 [info ] [MainThread]: Running with dbt=1.6.1
[0m21:44:25.762524 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt docs generate', 'send_anonymous_usage_stats': 'True'}
[0m21:44:25.763524 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m21:44:25.764524 [debug] [MainThread]: Command `dbt docs generate` failed at 21:44:25.764524 after 0.02 seconds
[0m21:44:25.765524 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C6C6D7E890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C6C5E7B430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C6C5E7B760>]}
[0m21:44:25.765524 [debug] [MainThread]: Flushing usage events
[0m21:51:38.649894 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB595A2860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB586AF6D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB586AF4F0>]}


============================== 21:51:38.654904 | f2036619-15a4-45cf-89d0-42b6582216de ==============================
[0m21:51:38.654904 [info ] [MainThread]: Running with dbt=1.6.1
[0m21:51:38.655899 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt docs generate', 'send_anonymous_usage_stats': 'True'}
[0m21:51:38.656908 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m21:51:38.659905 [debug] [MainThread]: Command `dbt docs generate` failed at 21:51:38.659905 after 0.03 seconds
[0m21:51:38.659905 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB595A2860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB586AF400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB586AF730>]}
[0m21:51:38.660909 [debug] [MainThread]: Flushing usage events
[0m22:37:37.743017 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DD49BCE8F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DD48CCB6A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DD48CCB4C0>]}


============================== 22:37:37.748017 | 23b97490-7cfa-43fe-8579-4db15f54284a ==============================
[0m22:37:37.748017 [info ] [MainThread]: Running with dbt=1.6.1
[0m22:37:37.749022 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt compile -m --profiles-dir jaffle_shop/models/marts/dim_customers.sql', 'send_anonymous_usage_stats': 'True'}
[0m22:37:37.750017 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m22:37:37.751017 [debug] [MainThread]: Command `dbt compile` failed at 22:37:37.751017 after 0.02 seconds
[0m22:37:37.752017 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DD49BCE8F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DD48CCB3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DD48CCB700>]}
[0m22:37:37.753002 [debug] [MainThread]: Flushing usage events
[0m23:00:29.098961 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8A708E860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8A618AA70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8A618AE30>]}


============================== 23:00:29.103956 | 9a1598e0-60c8-47e7-b0a1-d6a8a6e8e372 ==============================
[0m23:00:29.103956 [info ] [MainThread]: Running with dbt=1.6.1
[0m23:00:29.104948 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'jaffle_shop/models/marts/dim_customers.sql', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt compile -m . --profiles-dir jaffle_shop/models/marts/dim_customers.sql', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:00:29.105962 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:00:29.106957 [debug] [MainThread]: Command `dbt compile` failed at 23:00:29.105962 after 0.02 seconds
[0m23:00:29.106957 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8A708E860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8A618AE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8A618A9E0>]}
[0m23:00:29.107957 [debug] [MainThread]: Flushing usage events
[0m23:00:32.896831 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DDB7AE890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DDA8AB670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DDA8AB490>]}


============================== 23:00:32.901832 | 3150944e-8ddb-43ce-a0c5-aff25e3903b3 ==============================
[0m23:00:32.901832 [info ] [MainThread]: Running with dbt=1.6.1
[0m23:00:32.902834 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\kerry\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt test -m dim_customers+', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:00:32.903832 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\E\dbt_core_jaffle_shop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:00:32.904831 [debug] [MainThread]: Command `dbt test` failed at 23:00:32.904831 after 0.02 seconds
[0m23:00:32.905832 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DDB7AE890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DDA8AB3A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DDA8AB6D0>]}
[0m23:00:32.906832 [debug] [MainThread]: Flushing usage events
